# Generated by Django 4.0.4 on 2022-06-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_category_comment_bid_auction_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='descripction',
            new_name='description',
        ),
    ]
