# Generated by Django 4.0.5 on 2022-06-24 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='currentBid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentBidAuction', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='auctions.category'),
        ),
    ]
