# Generated by Django 4.0.5 on 2022-06-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_watchlist_auction_watchlist_auction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
