# Generated by Django 4.0.5 on 2022-06-25 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auction',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction',
            field=models.ManyToManyField(default=None, related_name='auctionWatchlist', to='auctions.auction'),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ManyToManyField(default=None, related_name='userWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
