# Generated by Django 4.0.5 on 2022-06-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_watchlist_auction_watchlist_auction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='auction',
            new_name='auctions',
        ),
    ]
